### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by hbellafkir** [Minione/DTSH#3]
Hi,

I'm trying to evaluate different approaches for image retrieval. Most of the other works (such as DPH, DTQ, CSQ) use AlexNet as backbone. Can you provide  an imagenet_alexnet.mat file? 

thanks

**Comment by Minione** [comment]
Sorry, we don't have that for alexnet. Our backbone and other experimental setup follow previous work DPSH (https://arxiv.org/abs/1511.03855).

**Comment by hbellafkir** [comment]
ok. I will take then this work out of the testing pool. Thanks for the answer.
